# This workflow periodically makes calls to the COHD API to verify it's operating as expected
name: COHD API Monitoring Workflow

on:
  # Schedule this workflow to run twice a day (at 0300 and 1500 UTC)
  schedule:
    - cron: '0 3/12 * * *'
  
  # Also allow manually triggering this workflow_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests pandas matplotlib bmt==0.8.12 reasoner-validator flask flask-cors flask-caching
        pip show reasoner-validator
  test_alive:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Test all COHD instances alive
      # Run /health checks on all COHD instances (dev, CI, Test, Prod)
      run: |
        pytest -s test_alive.py
  test_cohd_io:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Test COHD REST API
      # Test cohd.io by running pytest on test_cohd_io.py
      # pytest -s disables pytest from capturing print statements (i.e., print statements will appear in console)
      run: |
        pytest -s test_cohd_io.py
  test_cohd_trapi:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Test COHD TRAPI
      # Test COHD TRAPI endpoints by running pytest on test_cohd_trapi.py
      run: |
        pytest -s test_cohd_trapi.py
  test_cohd_covid_io:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Test covid.cohd.io
      # Test covid.cohd.io by running pytest on test_cohd_covid_io.py
      # pytest -s disables pytest from capturing print statements (i.e., print statements will appear in console)
      run: |
        pytest -s test_cohd_covid_io.py
